# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: note.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'note.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnote.proto\"2\n\x04Note\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"3\n\x11\x43reateNoteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\" \n\x12\x43reateNoteResponse\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\x0eGetNoteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"1\n\x0fGetNoteResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1f\n\x11\x44\x65leteNoteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteNoteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10ListNotesRequest\")\n\x11ListNotesResponse\x12\x14\n\x05notes\x18\x01 \x03(\x0b\x32\x05.Note2\xdd\x01\n\x0bNoteService\x12\x35\n\nCreateNote\x12\x12.CreateNoteRequest\x1a\x13.CreateNoteResponse\x12,\n\x07GetNote\x12\x0f.GetNoteRequest\x1a\x10.GetNoteResponse\x12\x35\n\nDeleteNote\x12\x12.DeleteNoteRequest\x1a\x13.DeleteNoteResponse\x12\x32\n\tListNotes\x12\x11.ListNotesRequest\x1a\x12.ListNotesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'note_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTE']._serialized_start=14
  _globals['_NOTE']._serialized_end=64
  _globals['_CREATENOTEREQUEST']._serialized_start=66
  _globals['_CREATENOTEREQUEST']._serialized_end=117
  _globals['_CREATENOTERESPONSE']._serialized_start=119
  _globals['_CREATENOTERESPONSE']._serialized_end=151
  _globals['_GETNOTEREQUEST']._serialized_start=153
  _globals['_GETNOTEREQUEST']._serialized_end=181
  _globals['_GETNOTERESPONSE']._serialized_start=183
  _globals['_GETNOTERESPONSE']._serialized_end=232
  _globals['_DELETENOTEREQUEST']._serialized_start=234
  _globals['_DELETENOTEREQUEST']._serialized_end=265
  _globals['_DELETENOTERESPONSE']._serialized_start=267
  _globals['_DELETENOTERESPONSE']._serialized_end=304
  _globals['_LISTNOTESREQUEST']._serialized_start=306
  _globals['_LISTNOTESREQUEST']._serialized_end=324
  _globals['_LISTNOTESRESPONSE']._serialized_start=326
  _globals['_LISTNOTESRESPONSE']._serialized_end=367
  _globals['_NOTESERVICE']._serialized_start=370
  _globals['_NOTESERVICE']._serialized_end=591
# @@protoc_insertion_point(module_scope)
